# Generated by Django 5.0.3 on 2024-12-06 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية العقد')),
                ('end_date', models.DateField(verbose_name='تاريخ نهاية العقد')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإيجار الشهري')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المقدم')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='ملف العقد')),
            ],
            options={
                'verbose_name': 'عقد إيجار',
                'verbose_name_plural': 'عقود الإيجار',
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المستأجر')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('national_id', models.CharField(max_length=50, unique=True, verbose_name='رقم الهوية الوطنية')),
                ('address', models.CharField(max_length=255, verbose_name='العنوان')),
            ],
            options={
                'verbose_name': 'مستأجر',
                'verbose_name_plural': 'المستأجرون',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=10, unique=True, verbose_name='رقم الوحدة')),
                ('unit_type', models.CharField(choices=[('office', 'مكتب'), ('apartment', 'شقة'), ('shop', 'محل')], max_length=10, verbose_name='نوع الوحدة')),
                ('floor_number', models.PositiveIntegerField(verbose_name='رقم الطابق')),
                ('size', models.FloatField(verbose_name='المساحة بالمتر المربع')),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الإيجار الشهري')),
                ('is_available', models.BooleanField(verbose_name='متاح')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الوحدة')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع')),
                ('payment_method', models.CharField(choices=[('cash', 'كاش'), ('credit_card', 'بطاقة الائتمان'), ('check', 'شيك')], max_length=50, verbose_name='طريقة الدفع')),
                ('description', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.lease', verbose_name='عقد الإيجار')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
            },
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.tenant', verbose_name='المستأجر'),
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الإنجاز')),
                ('is_completed', models.BooleanField(verbose_name='تم الإنجاز')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'طلب الصيانة',
                'verbose_name_plural': 'طلبات الصيانة',
            },
        ),
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.unit', verbose_name='الوحدة'),
        ),
    ]
