# Generated by Django 5.0.3 on 2024-12-08 13:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المبني')),
                ('location', models.TextField(verbose_name='موقع المبني')),
                ('facilities', models.TextField(blank=True, null=True, verbose_name='المرافق المتوفرة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
        ),
        migrations.CreateModel(
            name='Lease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=20, unique=True, verbose_name='رقم العقد')),
                ('start_date', models.DateField(verbose_name='تاريخ بداية العقد')),
                ('end_date', models.DateField(verbose_name='تاريخ نهاية العقد')),
                ('duration_months', models.PositiveIntegerField(verbose_name='مدة العقد (بالشهور)')),
                ('monthly_rent', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='الإيجار الشهري (ريال عماني)')),
                ('deposit', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المقدم (ريال عماني)')),
                ('contract_file', models.FileField(blank=True, null=True, upload_to='contracts', verbose_name='ملف العقد')),
                ('is_active', models.BooleanField(default=True, verbose_name='العقد نشط')),
            ],
            options={
                'verbose_name': 'عقد إيجار',
                'verbose_name_plural': 'عقود الإيجار',
                'ordering': ['start_date'],
            },
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المستأجر')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='البريد الإلكتروني')),
                ('national_id', models.CharField(max_length=15, unique=True, verbose_name='رقم البطاقة المدنية')),
                ('address', models.CharField(max_length=255, verbose_name='عنوان الإقامة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
            ],
            options={
                'verbose_name': 'مستأجر',
                'verbose_name_plural': 'المستأجرون',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='تاريخ الدفع')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='المبلغ المدفوع (ريال عماني)')),
                ('payment_method', models.CharField(choices=[('cash', 'نقداً'), ('bank_transfer', 'تحويل بنكي'), ('maintenance', 'بطاقة ائتمان')], max_length=20, verbose_name='طريقة الدفع')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.lease', verbose_name='عقد الإيجار')),
            ],
            options={
                'verbose_name': 'دفعة',
                'verbose_name_plural': 'الدفعات',
                'ordering': ['-date'],
            },
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='rental.building', verbose_name='المبني')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'مشرف',
                'verbose_name_plural': 'مشروفون',
            },
        ),
        migrations.AddField(
            model_name='lease',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.tenant', verbose_name='المستأجر'),
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unit_number', models.CharField(max_length=10, unique=True, verbose_name='رقم الوحدة')),
                ('unit_type', models.CharField(choices=[('office', 'مكتب'), ('apartment', 'شقة'), ('shop', 'محل تجاري')], max_length=10, verbose_name='نوع الوحدة')),
                ('floor_number', models.PositiveIntegerField(verbose_name='رقم الطابق')),
                ('size', models.FloatField(verbose_name='المساحة بالمتر المربع')),
                ('rent_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='سعر الإيجار الشهري (ريال عماني)')),
                ('electricity_meter_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم عداد الكهرباء')),
                ('water_meter_number', models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم عداد المياه')),
                ('status', models.CharField(choices=[('available', 'متاحة'), ('rented', 'مؤجرة'), ('maintenance', 'تحت الصيانة')], default='available', max_length=15, verbose_name='حالة الوحدة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف الوحدة')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='units', to='rental.building', verbose_name='المبني')),
            ],
            options={
                'verbose_name': 'وحدة',
                'verbose_name_plural': 'الوحدات',
                'ordering': ['unit_number'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(verbose_name='وصف المشكلة')),
                ('request_date', models.DateField(auto_now_add=True, verbose_name='تاريخ الطلب')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('in_progress', 'قيد التنفيذ'), ('completed', 'مكتملة')], default='pending', max_length=20, verbose_name='حالة الطلب')),
                ('start_date', models.DateField(blank=True, null=True, verbose_name='تاريخ بدء الإصلاح')),
                ('completion_date', models.DateField(blank=True, null=True, verbose_name='تاريخ إنهاء الصيانة')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rental.unit', verbose_name='الوحدة')),
            ],
            options={
                'verbose_name': 'طلب الصيانة',
                'verbose_name_plural': 'طلبات الصيانة',
                'ordering': ['-request_date'],
            },
        ),
        migrations.AddField(
            model_name='lease',
            name='unit',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental.unit', verbose_name='الوحدة'),
        ),
    ]
