# Generated by Django 5.1.4 on 2024-12-10 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupervisorPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='اسم الصلاحية')),
                ('description', models.TextField(verbose_name='وصف الصلاحية')),
            ],
            options={
                'verbose_name': 'صلاحية المشرف',
                'verbose_name_plural': 'صلاحيات المشرفين',
            },
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='نوع الوحدة')),
                ('description', models.TextField(blank=True, null=True, verbose_name='وصف')),
            ],
            options={
                'verbose_name': 'نوع الوحدة',
                'verbose_name_plural': 'أنواع الوحدات',
            },
        ),
        migrations.AddField(
            model_name='tenant',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='اسم الشركة'),
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='permissions',
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(help_text='يجب أن يكون البريد الإلكتروني فريداً', max_length=254, unique=True, verbose_name='البريد الإلكتروني'),
        ),
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=255, verbose_name='الإجراء')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='التاريخ والوقت')),
                ('details', models.TextField(blank=True, null=True, verbose_name='تفاصيل الإجراء')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'سجل النشاط',
                'verbose_name_plural': 'سجلات الأنشطة',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=20, unique=True, verbose_name='رقم الفاتورة')),
                ('issue_date', models.DateField(verbose_name='تاريخ الإصدار')),
                ('due_date', models.DateField(verbose_name='تاريخ الاستحقاق')),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='إجمالي المبلغ (ريال عماني)')),
                ('vat', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='ضريبة القيمة المضافة (%)')),
                ('paid', models.BooleanField(default=False, verbose_name='مدفوعة')),
                ('lease', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='rental.lease', verbose_name='عقد الإيجار')),
            ],
            options={
                'verbose_name': 'فاتورة',
                'verbose_name_plural': 'الفواتير',
                'ordering': ['-issue_date'],
            },
        ),
        migrations.CreateModel(
            name='MaintenanceReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(verbose_name=' (من 1 إلى 5) التقييم')),
                ('feedback', models.TextField(blank=True, null=True, verbose_name='الملاحظات')),
                ('maintenance_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='rental.maintenancerequest', verbose_name='طلب الصيانة')),
            ],
            options={
                'verbose_name': 'تقييم الصيانة',
                'verbose_name_plural': 'تقييمات الصيانة',
            },
        ),
        migrations.CreateModel(
            name='Notifiction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(verbose_name='نص التنبيه')),
                ('read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإنشاء')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='المستخدم')),
            ],
            options={
                'verbose_name': 'تنبيه',
                'verbose_name_plural': 'التنبيهات',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SupportMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255, verbose_name='الموضوع')),
                ('message', models.TextField(verbose_name='الرسالة')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإرسال')),
                ('read', models.BooleanField(default=False, verbose_name='مقروءة')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL, verbose_name='المستلم')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='المرسل')),
            ],
            options={
                'verbose_name': 'رسالة الدعم',
                'verbose_name_plural': 'رسائل الدعم',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rental.unittype', verbose_name='نوع الوحدة'),
        ),
        migrations.AddField(
            model_name='supervisor',
            name='permissions',
            field=models.ManyToManyField(blank=True, to='rental.supervisorpermission', verbose_name='الصلاحيات'),
        ),
    ]
