# Generated by Django 5.1.4 on 2024-12-07 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lease',
            options={'ordering': ['start_date'], 'verbose_name': 'عقد إيجار', 'verbose_name_plural': 'عقود الإيجار'},
        ),
        migrations.AlterModelOptions(
            name='maintenancerequest',
            options={'ordering': ['-request_date'], 'verbose_name': 'طلب الصيانة', 'verbose_name_plural': 'طلبات الصيانة'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-date'], 'verbose_name': 'دفعة', 'verbose_name_plural': 'الدفعات'},
        ),
        migrations.AlterModelOptions(
            name='tenant',
            options={'ordering': ['name'], 'verbose_name': 'مستأجر', 'verbose_name_plural': 'المستأجرون'},
        ),
        migrations.AlterModelOptions(
            name='unit',
            options={'ordering': ['unit_number'], 'verbose_name': 'وحدة', 'verbose_name_plural': 'الوحدات'},
        ),
        migrations.RemoveField(
            model_name='unit',
            name='is_available',
        ),
        migrations.AddField(
            model_name='lease',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='العقد نشط'),
        ),
        migrations.AddField(
            model_name='maintenancerequest',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية'),
        ),
        migrations.AddField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='ملاحظات إضافية'),
        ),
        migrations.AddField(
            model_name='unit',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default='', verbose_name='تاريخ الإنشاء'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.CharField(choices=[('available', 'متاحة'), ('rented', 'مؤجرة'), ('maintenance', 'تحت الصيانة')], default='available', max_length=15, verbose_name='حالة الوحدة'),
        ),
        migrations.AddField(
            model_name='unit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'نقدا'), ('credit_card', 'بطاقة الائتمان'), ('check', 'شيك')], max_length=50, verbose_name='طريقة الدفع'),
        ),
    ]
