# Generated by Django 5.1.4 on 2024-12-08 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maintenancerequest',
            name='is_completed',
        ),
        migrations.AddField(
            model_name='unit',
            name='electricity_meter_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم عداد الكهرباء'),
        ),
        migrations.AddField(
            model_name='unit',
            name='water_meter_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='رقم عداد المياه'),
        ),
        migrations.AlterField(
            model_name='maintenancerequest',
            name='completion_date',
            field=models.DateField(blank=True, null=True, verbose_name='تاريخ إنهاء الصيانة'),
        ),
    ]
