# Generated by Django 5.0.3 on 2024-12-11 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='permissions',
        ),
        migrations.AlterModelOptions(
            name='notifiction',
            options={'ordering': ['-created_at'], 'verbose_name': 'إشعار', 'verbose_name_plural': 'الإشعارات'},
        ),
        migrations.AddField(
            model_name='building',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان المبني'),
        ),
        migrations.AddField(
            model_name='lease',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='الخصم (ريال عماني)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lease',
            name='status',
            field=models.CharField(choices=[('active', 'نشط'), ('expired', 'منتهي'), ('suspended', 'معلق')], default='active', max_length=10, verbose_name='حالة العقد'),
        ),
        migrations.AddField(
            model_name='notifiction',
            name='type',
            field=models.CharField(choices=[('payment_due', 'إشعار مستحقات'), ('maintenance_update', 'تحديث صيانة'), ('lease_update', 'تحديث عقد')], default=1, max_length=20, verbose_name='نوع الإشعار'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='عنوان الوحدة'),
        ),
        migrations.AlterField(
            model_name='lease',
            name='deposit',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='مقدم (ريال عماني)'),
        ),
        migrations.AlterField(
            model_name='notifiction',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإشعار'),
        ),
        migrations.AlterField(
            model_name='notifiction',
            name='message',
            field=models.TextField(verbose_name='نص الإشعار'),
        ),
        migrations.AlterField(
            model_name='notifiction',
            name='read',
            field=models.BooleanField(default=False, verbose_name='تمت القراءة'),
        ),
        migrations.DeleteModel(
            name='SupervisorPermission',
        ),
    ]
