# Generated by Django 3.1.12 on 2024-12-06 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='building',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'كاش'), ('credit_card', 'بطاقة الائتمان'), ('check', 'شيك')], default='', max_length=50, verbose_name='طريقة الدفع'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='address',
            field=models.CharField(default='', max_length=255, verbose_name='العنوان'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tenant',
            name='national_id',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='رقم الهوية الوطنية'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='unit',
            name='unit_number',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='رقم الوحدة'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Building',
        ),
    ]
