# Generated by Django 5.0.3 on 2024-12-11 11:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_supervisor_permissions_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='unit',
            name='address',
        ),
    ]
