# Generated by Django 5.1.4 on 2024-12-10 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_supervisorpermission_unittype_tenant_company_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supervisorpermission',
            name='description',
            field=models.TextField(blank=True, verbose_name='وصف الصلاحية'),
        ),
    ]
