# Generated by Django 3.1.12 on 2024-12-06 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_auto_20241206_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='floor_number',
            field=models.PositiveIntegerField(default='', verbose_name='رقم الطابق'),
            preserve_default=False,
        ),
    ]
