# Generated by Django 5.1.4 on 2024-12-08 13:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_remove_maintenancerequest_is_completed_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم المبني')),
                ('location', models.TextField(verbose_name='موقع المبني')),
                ('facilities', models.TextField(blank=True, null=True, verbose_name='المرافق المتوفرة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
        ),
        migrations.RemoveField(
            model_name='tenant',
            name='commercial_record',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='unit',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='unit',
            name='building',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='units', to='rental.building', verbose_name='المبني'),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='Supervisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('building', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supervisors', to='rental.building', verbose_name='المبني')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='supervisor', to=settings.AUTH_USER_MODEL, verbose_name='حساب المستخدم')),
            ],
            options={
                'verbose_name': 'مشرف',
                'verbose_name_plural': 'مشروفون',
            },
        ),
    ]
