# Generated by Django 5.1.4 on 2024-12-10 11:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_supervisorpermission_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='permissions',
        ),
    ]
