# Generated by Django 5.0.3 on 2024-12-12 12:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_remove_invoice_paid_remove_invoice_vat_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supervisor',
            name='building',
        ),
        migrations.RemoveField(
            model_name='supervisor',
            name='user',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='recipient',
        ),
        migrations.RemoveField(
            model_name='supportmessage',
            name='sender',
        ),
        migrations.AlterField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(default=1, max_length=50, verbose_name='نوع الوحدة'),
            preserve_default=False,
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'دفعة', 'verbose_name_plural': 'الدفعات'},
        ),
        migrations.RemoveField(
            model_name='notifiction',
            name='type',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='date',
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_date',
            field=models.DateField(auto_now_add=True, default=1, verbose_name='تاريخ الدفع'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='payment',
            name='lease',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='rental.lease', verbose_name='عقد الإيجار'),
        ),
        migrations.DeleteModel(
            name='MaintenanceReview',
        ),
        migrations.DeleteModel(
            name='Supervisor',
        ),
        migrations.DeleteModel(
            name='SupportMessage',
        ),
        migrations.DeleteModel(
            name='UnitType',
        ),
    ]
